protected/models/Contest.php
<?php

/**
 * This is the model class for table "contests".
 *
 * The followings are the available columns in table 'contests':
 * @property integer $id
 * @property string $name
 * @property string $author
 * @property string $date_from
 * @property string $date_to
 * @property string $created
 * @property string $modified
 * @property string $description
 * @property string $more_requirements
 * @property string $more_label
 * @property string $prize
 * @property string $more_prize
 * @property string $vk
 * @property string $facebook
 * @property string $twitter
 * @property string $downloads
 * @property string $video
 * @property string $audio
 * @property string $web
 * @property string $slide
 */
class Contest extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Contest the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'contests';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, date_from, date_to', 'required'),
			array('name,  vk, facebook, twitter, web, slide', 'length', 'max'=>255),
			array('title', 'length', 'max'=>100),

			array(
				'id, description_under,  name, author, date_from, date_to, created, modified, description,
				 cover, more_requirements,
				 more_label, prize, more_prize, vk, facebook, twitter, downloads, video, audio, web, slide',
				'safe'
			),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => t('Name'),
            'author' => t('Author'),
			'date_from' => t('Date From'),
			'date_to' => t('Date To'),
			'created' => t('Created'),
			'modified' => t('Modified'),
			'description' => t('Description'),
			'description_under' => t('Description Second'),
			'more_requirements' => t('More Requirements'),
			'more_label' => t('More Label'),
			'prize' => t('Prize'),
			'more_prize' => t('More Prize'),
			'vk' => t('Vk'),
			'facebook' => t('Facebook'),
			'twitter' => t('Twitter'),
			'downloads' => t('Downloads'),
			'video' => t('Video'),
			'audio' => t('Audio'),
			'web' => t('Web'),
			'slide' => t('Slide'),
			'contest' => t('Contest'),
			'title' => 'Заголовок "О Конкурсе"'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('date_from',$this->date_from,true);
		$criteria->compare('date_to',$this->date_to,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('modified',$this->modified,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('more_requirements',$this->more_requirements,true);
		$criteria->compare('more_label',$this->more_label,true);
		$criteria->compare('prize',$this->prize,true);
		$criteria->compare('more_prize',$this->more_prize,true);
		$criteria->compare('vk',$this->vk,true);
		$criteria->compare('facebook',$this->facebook,true);
		$criteria->compare('twitter',$this->twitter,true);
		$criteria->compare('downloads',$this->downloads,true);
		$criteria->compare('video',$this->video,true);
		$criteria->compare('audio',$this->audio,true);
		$criteria->compare('web',$this->web,true);
		$criteria->compare('slide',$this->slide,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    protected function beforeSave()
    {
        if(parent::beforeSave())
        {
            if($this->isNewRecord)
            {
                $this->created = date('Y-m-d H:i:s');
            }

            $this->modified = date('Y-m-d H:i:s');

            return true;
        }

        return false;
    }

	public function getStat()
	{
		$id = $this->id;
		$downloads = DowloadsStat::model()->findAll( 'contest_id = :cid', array(':cid' => $id ) );
		$remixes   = Remix::model()->findAll( 'contest_id = :cid', array(':cid' => $id));

		$download_stat = 0;
		$remixes_stat = 0;

		if (!empty($downloads)) {
			$download_stat = count($downloads);
		}

		if (!empty($remixes)) {
			$remixes_stat =  count($remixes);
		}

		echo '<div class="icon icon-arrow-down" title="Скачиваний">' . $download_stat .'</div>' .
			 '<div class="icon icon-arrow-up" title="Загрузок ремиксов">'. $remixes_stat . '</div>';

	}
}

protected/controllers/ContestController.php
<?php

class ContestController extends Controller
{
	public $layout='//layouts/main';

	public function filters() {
		return array(
			'accessControl',
		);
	}

	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array(
				'allow',
				'actions' => array(
					'UploadCover','ChangeCover' , 'RemoveCover', 'UploadSlide', 'ChangeSlide',
					'RemoveSlide', 'UploadRemix', 'CreateRemix'
				),
				'users'   => array('@')
			),
			array('allow',
				'actions' =>array('create','update','delete', 'admin' ,'members', 'MemberView'),
				'roles'   =>array(User::ROlE_ADMIN),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionView($id)
	{
        Yii::app()->setTheme('sendremix');
		$this->SetUserModels();
		$meta = Meta::model()->find('id="'.Yii::app()->name.'"');
		$this->meta = $meta;
		$meta = Meta::getMetaModel();

		if ($meta) {
			$this->render('view',array(
				'model'		=> $this->loadModel($id),
				'modal_id'  => $this->getModalId(),
				'meta'      => $meta,
			));
		} else {
			throw new CHttpException(404,'Can\'t find site meta information. Please contact with administrator');
		}
	}

	public function actionCreate()
	{

		$model = new Contest;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Contest']))
		{
			$model->attributes = $_POST['Contest'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create', array(
			'model'=>$model,
		));
	}


	public function actionUpdate($id)
	{

		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Contest']))
		{
			$model->attributes = $_POST['Contest'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/*
	 * Upload remix by authorized user
	 * Remix file name is storing by session
    */
	public function actionCreateRemix()
	{
		$model = new User(User::SEND_REMIX);

		if(!empty(Yii::app()->session['remix'])){
			$model->file = Yii::app()->session['remix'];
		} else {

			$model->addError('file', 'Выберите файл ремикса');
		}
		unset(Yii::app()->session['remix']);
		$this->performAjaxValidationRemix($model);

		if(isset($_POST['User']))
		{
			$transaction = Yii::app()->db->beginTransaction();
			try{
				$user_id =  Yii::app()->user->id;
				$user = User::model()->findByPk($user_id);
				$user->attributes = $_POST['User'];

				if($user->save()){

					$parser = new CHtmlPurifier();
					$file = $parser->purify($_POST['User']['file']);

					$contest_id =  (int) $_POST['User']['contest_id'];
					$contest = Contest::model()->findByPk($contest_id);

					if (!empty($contest)) {

						$remix = new Remix();
						$remix->contest_id = $contest_id;
						$remix->user_id = $user->id;
						$remix->file_name = $file;
						$remix->original_file_name = Yii::app()->session['original_file_name'];

						$remix->save();
						unset(Yii::app()->session['original_file_name']);
						$transaction->commit();

					} else {
						$user->addError('contest_id', 'Wrong contest information');
						$transaction->rollback();
					}

				}
			} catch (Exception $e) {
				$transaction->rollback();
				echo $e; die();
			}
		}
		$this->redirect('/thankyou');
	}

	public function actionUploadRemix()
	{
		Yii::import("ext.EAjaxUpload.qqFileUploader");
		$folder = dirname(Yii::getPathOfAlias('application')).'/uploads/remixes/';
		$allowedExtensions = array('mp3');
		$sizeLimit = 20 * 1024 * 1024;
		$uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
		$result = $uploader->handleUpload($folder, true);
		Yii::app()->session['remix'] = $result['filename'];
		Yii::app()->session['original_file_name'] = $result['original_file_name'];
		$result = htmlspecialchars(json_encode($result), ENT_NOQUOTES);
		echo $result;
	}

	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	public function actionIndex()
	{
        Yii::app()->setTheme('sendremix');
        $models = Contest::model()->findAll();
		$partners = Partner::model()->findAll();
        $meta = Meta::model()->find('id="'.Yii::app()->name.'"');
		$this->meta = $meta;
		$modal_id =  $this->GetModalId();
		$this->SetUserModels();
		$this->render('index', compact('models', 'meta', 'modal_id', 'partners'));
	}

	public function actionAdmin()
	{
		$downloads = DowloadsStat::model()->findAll();
		$remixes   = Remix::model()->findAll();

		$download_stat = 0;
		$remixes_stat = 0;

		if (!empty($downloads)) {
			$download_stat = count($downloads);
		}

		if (!empty($remixes)) {
			$remixes_stat =  count($remixes);
		}

		$model = new Contest('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Contest']))
			$model->attributes = $_GET['Contest'];

		$this->render('admin', array(
			'model' 		=> $model,
			'download_stat' => $download_stat,
			'remixes_stat'  => $remixes_stat,
		));
	}

	public function actionMembers()
	{

		$model = new Remix('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Contest']))
			$model->attributes = $_GET['Contest'];

		$this->render('members', array(
			'model' => $model,
		));
	}

	public function actionMemberView($id)
	{

		$model = Remix::model()->with('user','contest')->findByPk($id);
		if (!empty($model)) {


			$this->render( 'member_view', array (
				'model' => $model,
			));
		} else {
			throw new CHttpException(404,'The requested page does not exist.');
		}
	}


    public function actionUploadCover()
    {
        Yii::import("ext.EAjaxUpload.qqFileUploader");
        $folder = dirname(Yii::getPathOfAlias('application')).'/uploads/';
        $allowedExtensions = array("jpg");
        $sizeLimit = 10 * 1024 * 1024;
        $uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
        $result = $uploader->handleUpload($folder, true);

        $result = htmlspecialchars(json_encode($result), ENT_NOQUOTES);
        echo $result;
    }


    public function actionChangeCover()
    {
        $filename = $_POST['filename'];
        $contest = Contest::model()->findByPk($_GET['id']);
        $contest->cover = $filename;
        $contest->save(false);
    }

    public function actionRemoveCover()
    {
        $contest = User::model()->findByPk($_GET['id']);
        $contest->cover = '';
        $contest->save(false);
        $contest->redirect(array('admin'));
    }

    public function actionUploadSlide()
    {
        Yii::import("ext.EAjaxUpload.qqFileUploader");
        $folder = dirname(Yii::getPathOfAlias('application')).'/uploads/';
        $allowedExtensions = array("jpg");
        $sizeLimit = 10 * 1024 * 1024;
        $uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
        $result = $uploader->handleUpload($folder, true);

        $result = htmlspecialchars(json_encode($result), ENT_NOQUOTES);
        echo $result;
    }

    public function actionChangeSlide()
    {
        $filename = $_POST['filename'];
        $contest = Contest::model()->findByPk($_GET['id']);
        $contest->slide = $filename;
        $contest->save(false);
    }

    public function actionRemoveSlide()
    {
        $contest = Contest::model()->findByPk($_GET['id']);
        $contest->slide = '';
        $contest->save(false);
        $this->redirect(array('update', 'id'=>$_GET['id']));
    }


	/*	Subject to user authorized or not
	 *  this method create $user variable
	 *  with right validation scenario
	 * */
	private function setUserModels()
	{
		$is_guest = Yii::app()->user->isGuest;
		if($is_guest) {

			$this->model = new LoginForm();
			$this->user = new User(User::SIGNUP);
		} else {
			$this->user = new User(User::SEND_REMIX);
			$user_id = Yii::app()->user->id;
			$user  = User::model()->findByPk($user_id);
			$this->user = $user;
		}

	}

	/*
		if user doesn't login and click to upload remix,
		his must register or auth before and we need to show
		him right modal window
	*/
	private function getModalId()
	{
		$is_guest = Yii::app()->user->isGuest;
		if($is_guest) {
			return  '#modal_01';
		} else {
			return	'#modal-send-remix';
		}
	}

	public function loadModel($id)
	{
		$model = Contest::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model)
	{

		if(isset($_POST['ajax']) && $_POST['ajax'] === 'contest-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	protected function performAjaxValidationRemix($model)
	{

		if(isset($_POST['ajax']) && $_POST['ajax'] === 'remix-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/contest/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'contest-form',
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<?php if( !$model->isNewRecord) {?>
    <div class="row">
        <?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
            'buttons'=>array(
                array(
                    'label' => t('Change slide').' 1349 x 530',
                    'icon'=>'picture',
                    'htmlOptions'=>array(
                        'data-toggle'=>'modal',
                        'data-target'=>'#uploadSlide',
                    ),
                ),
                array('items'=>array(
                    array('label' => t('Remove slide'), 'url'=>array('/contest/removeSlide?id='.$model->id)),
                )),
            ),
        )); ?>
        <br><br>
    </div>

    <div class="row contest-slide">
        <?php if($model->slide): ?>
            <img id="slide" src="<?php echo $model->slide ?>">
        <?php else: ?>
            <img id="slide" src="/images/slide.png">
        <?php endif;?>
    </div>
    <br><br>

    <div class="row">
        <?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
            'buttons'=>array(
                array(
                    'label' => t('Change cover').' 220 x 288',
                    'icon'=>'picture',
                    'htmlOptions'=>array(
                        'data-toggle'=>'modal',
                        'data-target'=>'#uploadCover',
                    ),
                ),
                array('items'=>array(
                    array('label' => t('Remove cover'), 'url'=>array('/contest/removeCover?id='.$model->id)),
                )),
            ),
        )); ?>
        <br><br>
    </div>

    <div class="row contest-cover">
        <?php if($model->cover): ?>
            <img id="cover" src="<?php echo $model->cover ?>">
        <?php else: ?>
            <img id="cover" src="/images/cover.png">
        <?php endif;?>
    </div>
    <br><br>
	<?} else {?>
		<p>*Загрузка слайда и обложки конкурса доступно после его создания</p>
	<?php }?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textFieldRow($model,'author',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textAreaRow($model,'description',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

    <?php echo $form->textAreaRow($model,'description_under',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'date_from',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'date_to',array('class'=>'span5')); ?>

    <?php echo $form->textAreaRow($model,'video',array('rows'=>6, 'cols'=>50, 'class'=>'span8 mceNoEditor')); ?>

    <?php echo $form->textAreaRow($model,'audio',array('rows'=>6, 'cols'=>50, 'class'=>'span8 mceNoEditor')); ?>

    <?php echo $form->textFieldRow($model, 'downloads',array('class'=>'span5')); ?>

    <!--div class="row">
        <?php $this->widget('bootstrap.widgets.TbButtonGroup', array(
            'buttons'=>array(
                array(
                    'label' => t('Add downloads').' (zip)',
                    'icon'=>'picture',
                    'htmlOptions'=>array(
                        'data-toggle'=>'modal',
                        'data-target'=>'#uploadDownloads',
                    ),
                ),
                array('items'=>array(
                    array('label' => t('Remove downloads'), 'url'=>array('/contest/removeDownloads?id='.$model->id)),
                )),
            ),
        )); ?>
        <br><br>
    </div-->

    <!--div class="row contest-cover">
        <?php if($model->downloads): ?>
            <div id="downloads"><?php echo $model->downloads ?></div>
        <?php else: ?>
            <div id="downloads"><?php echo t('No file') ?></div>
        <?php endif;?>
    </div-->
    <br><br>

	<?php echo $form->textAreaRow($model,'more_requirements',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textAreaRow($model,'more_label',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textAreaRow($model,'prize',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textAreaRow($model,'more_prize',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

    <?php echo $form->textFieldRow($model,'web',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'vk',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'facebook',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'twitter',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? t('Create') : t('Save'),
		)); ?>
	</div>

<?php $this->endWidget(); ?>

<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'uploadCover')); ?>

    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4><?=t('Upload Cover')?></h4>
    </div>

    <div class="modal-body">
        <?php
        $this->widget('ext.EAjaxUpload.EAjaxUpload',
            array(
                'id' => 'uploadFile',
                'config' => array(
                    'action' => Yii::app()->createUrl('/contest/uploadCover'),
                    'allowedExtensions' => array("jpg", "jpeg", "gif", "png"),
                    'sizeLimit' => 10*1024*1024,
                    'minSizeLimit' => 1,
                    'onComplete'=>"js:function(id, fileName, responseJSON){
					$('#cover').attr('src', '/uploads/'+responseJSON.filename);
					$.post('".Yii::app()->createUrl('/contest/changeCover')."?id=".$model->id."', {filename: '/uploads/' + responseJSON.filename});
				}"
                )
            ));
        ?>
    </div>

    <div class="modal-footer">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label' => t('Close'),
            'url' => '#',
            'htmlOptions' => array('data-dismiss'=>'modal'),
        )); ?>
    </div>

<?php $this->endWidget(); ?>

<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'uploadSlide')); ?>

    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4><?=t('Upload Slide')?></h4>
    </div>

    <div class="modal-body">
        <?php
        $this->widget('ext.EAjaxUpload.EAjaxUpload',
            array(
                'id' => 'uploadFileSlide',
                'config' => array(
                    'action' => Yii::app()->createUrl('/contest/uploadSlide'),
                    'allowedExtensions' => array("jpg", "jpeg", "gif", "png"),
                    'sizeLimit' => 10*1024*1024,
                    'minSizeLimit' => 1,
                    'onComplete'=>"js:function(id, fileName, responseJSON){
					$('#slide').attr('src', '/uploads/'+responseJSON.filename);
					$.post('".Yii::app()->createUrl('/contest/changeSlide')."?id=".$model->id."', {filename: '/uploads/' + responseJSON.filename});
				}"
                )
            ));
        ?>
    </div>

    <div class="modal-footer">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label' => t('Close'),
            'url' => '#',
            'htmlOptions' => array('data-dismiss'=>'modal'),
        )); ?>
    </div>

<?php $this->endWidget(); ?>


<!--?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'uploadDownloads')); ?>

    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4><?=t('Upload Downloads')?></h4>
    </div>

    <div class="modal-body">
        <?php
        $this->widget('ext.EAjaxUpload.EAjaxUpload',
            array(
                'id' => 'uploadFileDownloads',
                'config' => array(
                    'action' => Yii::app()->createUrl('/contest/uploadDownloads'),
                    'allowedExtensions' => array("zip"),
                    'sizeLimit' => 10*1024*1024,
                    'minSizeLimit' => 1,
                    'onComplete'=>"js:function(id, fileName, responseJSON){
					$('#downloads').html(responseJSON.filename);
					$.post('".Yii::app()->createUrl('/contest/changeDownloads')."?id=".$model->id."', {filename: '/uploads/' + responseJSON.filename});
				}"
                )
            ));
        ?>
    </div>

    <div class="modal-footer">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label' => t('Close'),
            'url' => '#',
            'htmlOptions' => array('data-dismiss'=>'modal'),
        )); ?>
    </div -->

<?//php $this->endWidget(); ?>

protected/views/contest/admin.php
<?php
$this->breadcrumbs=array(
    t('Content')=>array('/site/meta'),
	t('Contests'),
);
?>
<h1><?php echo t('Manage Contests')?></h1>


<?php echo CHtml::link(t('Create Contest'), array('/contest/create'), array('class'=>'btn btn-primary')); ?>
<br/>
<br/>
<span class="label label-warning arrowed arrowed-right">Общая статистика</span>
<br/>
<br/>
<div class="infobox infobox-grey infobox-small infobox-dark">
	<div class="infobox-icon">
		<i class="icon-download-alt"></i>
	</div>

	<div class="infobox-data">
		<div class="infobox-content">Загрузки</div>
		<div class="infobox-content"> <?php echo $download_stat?></div>
	</div>
</div>

<div class="infobox infobox-green infobox-small infobox-dark">
	<div class="infobox-icon">
		<i class="icon-download-alt"></i>
	</div>

	<div class="infobox-data">
		<div class="infobox-content">Ремиксы</div>
		<div class="infobox-content"><?php echo $remixes_stat?></div>
	</div>
</div>


<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'contest-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'name',
		'date_from',
		'date_to',

		'contest'=>array(
			'value' => "'<img src=\"/assets/admin/images/move.png\" />'",
			'header' => t('Contest'),
			'value'  => '$data->getStat()',

		),

		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/contest/index.php
<h1><?=t('Contests'); ?></h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/contest/member_view.php
<?php
$this->breadcrumbs=array(
    t('Content')=>array('/site/meta'),
	t('Members'),
);


?>
<?php echo CHtml::link('Вернуться назад', array('/contest/members')) ?>

<br/>
<br/>

<div class="view">
	<?php $user = $model->user();?>
	<?php $this->widget('bootstrap.widgets.TbDetailView', array(
		'data'=> $model,
		'attributes'=>array(

			'contest' => array(
				'name' =>  t('Contest'),
				'value' => $model->contest()->name
			),
			'user_id' => array(
				'name' => t('Member'),
				'value' => $user->last_name    . ' ' .
						   $user->first_name   . ' ' .
						   $user->second_name
			),

			'file_name' => array(
				'type'   =>'raw',
				'name'  => t('Remix'),
				'value' => CHtml::link($model->file_name, Remix::get_path($model->file_name))
			),


			'created_on' => array(
				'name' => t('Date Added'),
				'value' => $model->get_create_on()
			),

			'phone' => array(
				'name' => t('Phone'),
				'value' => $user->phone,
			),
			'country' => array(
				'name' => t('Country'),
				'value' => $user->country,
			),
			'city' => array(
				'name' => t('City'),
				'value' => $user->city,
			),

			'email' => array(
				'name' => 'email',
				'value' => $user->email,
			),
			'website' => array(
				'name' => t('Website'),
				'value' => $user->website,
			),


			'photo' => array(
				'type'=>'html',
				'name' => 'Фото',
				'value' => '<img width="300px" src="' .$user->getPhoto() .'"/>',
			),





		),
	)); ?>

</div>