protected/models/User.php
<?php

class User extends CActiveRecord
{
	/* Scenarios */

	const SIGNUP     = 'signup';
	const PROFILE    = 'profile';
	const PASSWORD   = 'password';
	const SEND_REMIX = 'send_remix';
	const CREATE     = 'user_create';

	/* Roles */
	const ROlE_GUEST  = 0;
	const ROlE_ADMIN  = 2;
	const ROLE_USER   = 1;

	public static $dir = '/uploads/';
	public $passwordRepeat;

	public $acceptRules;
	public $contest_id;
	public $file;

	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function tableName()
	{
		return 'users';
	}


	public function rules()
	{
        return array(
			array(
				'email, password, passwordRepeat',
				'required',
				'on' => self::CREATE
			),
            array(
                ' first_name, email, password, passwordRepeat',
                //'acceptRules, first_name, email, , passwordRepeat',
                'required',
                'on' => self::SIGNUP,
                'message' => t('Fill {attribute}')
            ),
            array(
                'first_name, email',
                'required',
                'on' => self::PROFILE,
                'message' => t('Fill {attribute}')
            ),

			array('first_name, last_name, email, phone, website, photo, city, country', 'filter', 'filter'=>array($obj=new CHtmlPurifier(),'purify')),

  			array(
                'first_name, second_name, last_name, email, phone,  city, country, file',
                'required',
                'on' => self::SEND_REMIX,
                'message' => t('Fill {attribute}')
            ),
			array(
				'acceptRules',
				'required',
				'requiredValue' => 1,
				'on' => array(self::SEND_REMIX,  self::SIGNUP),
				'message' => t('You must be accept rules')
			),
            //array('email, password', 'required', 'on' => self::LOGIN, 'message' => t('Fill {attribute}')),

            array('email, phone', 'unique', 'on' => array(self::SIGNUP, self::CREATE), 'message' => t('This {attribute} is already registered')),
            array(
                'email, password',
                'length',
                'max' => 255,
                'on' => self::SIGNUP,
                'message' => t('Max length of {attribute} is 255')
            ),
            array(
                'phone',
                'length',
                'max' => 20,
                'on' => self::SIGNUP,
                'message' => t('{attribute} should be max 20 digits')
            ),
            array(
                'password',
                'compare',
                'compareAttribute' => 'passwordRepeat',
                'on' => self::SIGNUP,
                'message' => t('Passwords does not match')
            ),
            array('id, email, phone, password, first_name, last_name, second_name, country, city, vkontakte, facebook, twitter, google, instagram, languages, skills, birth_date, nickname, language', 'safe'),
            array(
                'email',
                'filter',
                'filter' => 'mb_strtolower',
                'on' => self::SIGNUP,
                'message' => t('{attribute} should be in lower case')
            ),
            array('email', 'email', 'on' => self::SIGNUP),
        );
	}


	public function relations()
	{
		return array(
			'remixes' => array(self::HAS_MANY, 'Remix', 'user_id')
		);
	}


	public function attributeLabels()
	{
		return array(
            'id' 				=> 'Id',
            'first_name' 		=> t('First Name'),
            'second_name' 		=> t('Second Name'),
            'last_name' 		=> t('Family Name'),
            'birth_date' 		=> t('Birth Date'),
            'nickname' 			=> t('Nick Name'),
            'email' 			=> t('Email'),
            'phone' 			=> t('Phone'),
            'website' 			=> t('Web Site'),
            'password'			=> t('Password'),
            'passwordRepeat' 	=> t('Repeat Password'),
            'photo' 			=> t('Photo'),
            'country' 			=> t('Country of residence'),
            'city' 				=> t('City of residence'),
            'vkontakte' 		=> t('Vkontakte'),
            'facebook' 			=> t('Facebook'),
            'twitter' 			=> t('Twitter'),
            'google' 			=> t('Google+'),
            'instagram' 		=> t('Instagram'),
            'languages' 		=> t('Languages'),
            'accept_rules' 		=> t('Accept Rules'),
            'role' 		        => t('Role'),
		);
	}


	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);

		$criteria->compare('last_name',$this->first_name,true);
		$criteria->compare('first_name',$this->last_name,true);
		$criteria->compare('email',$this->email,true);

		$criteria->compare('phone',$this->phone,true);

		$criteria->compare('password',$this->password,true);

		return new CActiveDataProvider('User', array(
			'criteria'=>$criteria,
		));
	}

	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->email == 'admin'){
				$this->addError('email', 'you can\'t delete or change admin user');
				return false;
			}

			if($this->isNewRecord)
			{
				$this->registered = date('Y-m-d H:i:s');
                $this->password = self::hashPassword($this->password);
			}
			
			if($this->scenario == self::PASSWORD)
			{
				$this->password = self::hashPassword($this->password);
			}
	
			return true;
		}
	
		return false;
	}





	static function hashPassword($password)
	{
		return md5($password);
	}
	
	public function login()
	{
		$identity = new UserIdentity($this->email, $this->password);
		if($identity->authenticate()) {
			Yii::app()->user->login($identity);
			return true;
		} else {
			$this->addError('email', t('Incorrect username or password.'));
			return false;
		}
	}

	public function getPhoto()
	{
		if (!empty($this->photo)){
			return  $this->photo;
		}
		else {
			return Yii::app()->theme->baseUrl  . '/images/no_image.gif';
		}
	}
	public static function getRolesList()
	{
		return array(
			 self::ROLE_USER  => t('User')  ,
			 self::ROlE_ADMIN => t('Admin') ,
		);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	public $layout='//layouts/main';


	public function filters() {
		return array(
			'accessControl',
		);
	}

	public function accessRules()
	{
		return array(
			array('allow',
				'roles' => array(User::ROlE_ADMIN),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionCreate()
	{
		$model = new User(User::CREATE);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{

			$model->attributes = $_POST['User'];
			$model->role = $_POST['User']['role'];

			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		if ($model->email != 'admin') {
			$model->delete();
		}
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}


	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}


	public function actionAdmin()
	{
		$model = new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id' => 'user-form',
	'enableAjaxValidation' => true,
)); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<?php if($model->isNewRecord) {?>

		<div class="row">
			<?php echo $form->labelEx($model,'password'); ?>
			<?php echo $form->passwordField($model,'password', array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'password'); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx($model,'passwordRepeat'); ?>
			<?php echo $form->passwordField($model,'passwordRepeat', array('size'=>60,'maxlength'=>255)); ?>
			<?php echo $form->error($model,'passwordRepeat'); ?>
		</div>
	<?php }?>

	<div class="row">
		<?php echo $form->labelEx($model,'role'); ?>
		<?php echo $form->dropDownList($model,'role', User::getRolesList()); ?>
		<?php echo $form->error($model,'role'); ?>
	</div>


	<div class="row">
		<?php echo $form->labelEx($model,'phone'); ?>
		<?php echo $form->textField($model,'phone',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'phone'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'first_name'); ?>
		<?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'first_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'last_name'); ?>
		<?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'last_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'second_name'); ?>
		<?php echo $form->textField($model,'second_name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'second_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'website'); ?>
		<?php echo $form->textField($model,'website',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'website'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'photo'); ?>
		<?php echo $form->textField($model,'photo',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'photo'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'city'); ?>
		<?php echo $form->textField($model,'city',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'city'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'country'); ?>
		<?php echo $form->textField($model,'country',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'country'); ?>
	</div>


	<div class="row buttons">

		<?php echo CHtml::submitButton($model->isNewRecord ? t('Create') : t('Save')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/user/_search.php
<?php
/* @var $this UserController */
/* @var $model User */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'phone'); ?>
		<?php echo $form->textField($model,'phone',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'registered'); ?>
		<?php echo $form->textField($model,'registered'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'first_name'); ?>
		<?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'last_name'); ?>
		<?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'second_name'); ?>
		<?php echo $form->textField($model,'second_name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'website'); ?>
		<?php echo $form->textField($model,'website',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'photo'); ?>
		<?php echo $form->textField($model,'photo',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hash'); ?>
		<?php echo $form->textField($model,'hash',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'confirmed'); ?>
		<?php echo $form->textField($model,'confirmed'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'language'); ?>
		<?php echo $form->textField($model,'language',array('size'=>2,'maxlength'=>2)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'city'); ?>
		<?php echo $form->textField($model,'city',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'country'); ?>
		<?php echo $form->textField($model,'country',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'vk_id'); ?>
		<?php echo $form->textField($model,'vk_id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fb_id'); ?>
		<?php echo $form->textField($model,'fb_id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'sc_id'); ?>
		<?php echo $form->textField($model,'sc_id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/admin.php
<h1><?php echo t('Manage Users')?></h1>
<?php echo CHtml::link(t('Create User'), array('user/create'), array('class'=>'btn btn-primary')); ?>

<?php
$this->breadcrumbs=array(
	t('Users'),
);
?>
<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'email',
		'phone',

		'name' => array(
			'name' => 'first_name',
			'value' => '$data->first_name . " " . $data->last_name'
		),
		/*
		'last_name',
		'second_name',
		'website',
		'photo',
		'hash',
		'confirmed',
		'language',
		'city',
		'country',
		'vk_id',
		'fb_id',
		'sc_id',
		*/
		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}{delete}',
		),
	),
)); ?>

protected/views/user/create.php
<?php
$this->breadcrumbs = array(
	t('Users')  => array('admin'),
	t('Create'),
);
?>

<h1><?php echo t('Create User')?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/update.php
<?php
$this->breadcrumbs = array(
	t('Users')  => array('admin'),
	t('Create'),
);
?>

<h1><?php echo t('Update User')?> <?php echo $model->email; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>